Repository appsignal/public_config, pull requests merged in 2019-03, with the labels that each got.

#1 Add mongodb Dashboard
  dashboards/mongodb/main.yml
Labels: enhancement

#3 Add descriptions to dashboards
  dashboards/sidekiq/main.yml
  dashboards/unicorn/main.yml
Labels: enhancement

#4 Add Erlang metrics dashboard
  dashboards/erlang/main.yml
Labels: feature

#6 Remove Unicorn dashboard
  dashboards/unicorn/main.yml
Labels: chore

#7 Convert dashboards to new syntax
  dashboards/erlang/main.yml
  dashboards/mongodb/main.yml
  dashboards/sidekiq/main.yml
Labels: enhancement

#5 Add puma dashboard
  dashboards/puma/main.yml
Labels: enhancement

#9 Add hostname to ErlangVM metrics
  dashboards/erlang/main.yml
Labels: chore

#8 Limit Sidekiq metrics to background namespace
  dashboards/sidekiq/main.yml
Labels: bug

#10 Fix Sidekiq metric fields
  dashboards/sidekiq/main.yml
Labels: bug

#11 Add process_rss dashboard config
  dashboards/process_memory/main.yml
Labels: enhancement

#12 Add descriptions for puma dashboard graphs
  dashboards/puma/main.yml
Labels: enhancement
