Repository appsignal/public_config, pull requests merged in 2023-10, with the labels that each got.

#55 Add Vector PostgreSQL Auto Dashboard
  dashboards/postgres/README.md
  dashboards/postgres/main.json
Labels: feature

#58 Improve PostgreSQL dashboard labels and descriptions
  dashboards/postgres/main.json
Labels: enhancement

#56 Document Erlang magic dashboard
  dashboards/erlang/README.md
Labels: chore

#59 Update Erlang IO graph value format
  dashboards/erlang/main.json
Labels: chore
